### PR TITLE
Automatic generation of API documentation.

### PR DESCRIPTION
**Pull request by gislenius**

### CODE REVIEW

**Comment by wcandillon** [comment]
@gislenius Didn't we say that this file shouldn't be committed? (I thought I did it already). But I have no strong opinon.

**Comment by dknochen** [comment]
Is this file completely autogenerated?

**Comment by wcandillon** [comment]
completely

**Comment by dknochen** [comment]
then I agree that it should not be commited. It should be part of the build process.

**Comment by gislenius** [comment]
Hi Dennis,

What does this mean concretely? This file is already committed. Do you mean we should deactivate version control for it?

Kind regards,
Ghislain

**Comment by wcandillon** [comment]
@gislenius yes so this changes should be done in the swagger file.

**Comment by gislenius** [comment]
@wcandillon @dknochen I'm closing this PR with no merge.

**Pull request closed without merging**
