### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@dknochen I'm trying to fix the regression. Is this PR correct? Or should it be `err.getMessage().indexOf('NoSuchBucket:') === 0` ?

**Comment by dknochen** [comment]
I'm not sure about this. In the documentation it says its an error object: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketWebsite-property
Can you confirm this?

**Comment by wcandillon** [comment]
if you look at the latest master failure on circleci you will see the issue.

**Comment by dknochen** [comment]
then yes, should be 

    _.isString(err.message) && err.message.indexOf ...

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Response.html

**Comment by wcandillon** [comment]
@dknochen back to you.

**Comment by wcandillon** [comment]
@dknochen I think it still doesn't work.

**Pull request merged**
