### PR TITLE
fix check NoSuchBucket error

### PR DESCRIPTION
**Pull request by dknochen**

### CODE REVIEW

**Comment by dknochen** [comment]
image

**Comment by dknochen** [comment]
@wcandillon we could also use the retryDelay field, but maybe thats overdoing it?

**Comment by wcandillon** [comment]
yay!

**Comment by wcandillon** [comment]
@dknochen What's `retryDelay`?

**Comment by dknochen** [comment]
@wcandillon in the screenshot above you can see that "retryDelay: 30" is part of the response of S3. I think they want to suggest us that we should wait for 30 Seconds until we try again. Anyways, I don't believe we should follow this.

**Comment by wcandillon** [comment]
Thks for the info! I agree.

**Pull request merged**
