### PR TITLE
Dashboard improvements

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@dknochen Here's a link to try: `/dashboard/E02529/BalanceSheet/jppfs-cor:DeferredAssets,jp-t-cte:DeferredAssets/Deferred%20assets`

screenshot 2015-02-17 08 38 25

**Comment by wcandillon** [comment]
@dknochen @gislenius Merging this seems urgent since the dashboard doesn't seem to work with the new database that was deployed in production without these changes.

**Comment by wcandillon** [comment]
@dknochen `xbrl28:Consolidated` can be named anything right? As long as it doesn't collide with a non default value.

**Comment by dknochen** [comment]
>> @dknochen xbrl28:Consolidated can be named anything right? As long as it doesn't collide with a non default value.

@wcandillon yes. Didn't see it in the code. My fault.

**Comment by wcandillon** [comment]
@dknochen Review comments implemented. Example URL: `/dashboard/E01225/BalanceSheet/jp-t-cte:LongTermLoansPayable,jppfs-cor:LongTermLoansPayable/Long-term%20loans%20payable`
screenshot 2015-02-17 14 16 15

**Pull request merged**
