### PR TITLE
Report frames

### PR DESCRIPTION
**Pull request by gislenius**

### CODE REVIEW

**Comment by gislenius** [comment]
http://rendering.secxbrl.info/#?url=http:%2F%2Fsecxbrl-dev3.28.io%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-report.jq%3Ftoken%3Dfoobar%26report%3DCOMID-BSC-CF1-ISM-IEMIX-OILY-CashFlowStatement%26ticker%3Dko%26fiscalYear%3DALL%26fiscalPeriod%3DFY%26validate%3Dtrue

**Comment by fcavalieri** [comment]
Maybe related: https://github.com/google/web-starter-kit/issues/518

**Comment by gislenius** [comment]
Blocker: process out of memory.

**Comment by wcandillon** [comment]
@gislenius I'm taking a look

**Comment by wcandillon** [comment]
@gislenius The memory issue is fixed at #799. Once you memory issues is fixed, @gislenius you will have to fix the test suite. @dknochen you'll have to do the review.

**Comment by gislenius** [comment]
@dknochen The last step is to investigate why it won't open in the CSMS.

**Comment by gislenius** [comment]
@dknochen FYI here's the error from the JS console:

Error: getParentElementFromTree: function called without mandatory "elementID" parameter.
    at ensureParameter (http://localhost:9000/modules/report-model.js:125:19)
    at AbstractReport.getParentElementFromTree (http://localhost:9000/modules/report-model.js:718:9)
    at AbstractReport.isRootElement (http://localhost:9000/modules/report-model.js:871:27)
    at http://localhost:9000/report/taxonomy/taxonomy.js:93:30
    at Array.forEach (native)
    at setPresentationTree (http://localhost:9000/report/taxonomy/taxonomy.js:84:12)
    at Scope.$scope.loadPresentationTree (http://localhost:9000/report/taxonomy/taxonomy.js:106:9)
    at new <anonymous> (http://localhost:9000/report/taxonomy/taxonomy.js:109:12)
    at invoke (http://localhost:9000/bower_components/angular/angular.js:3710:17)
    at Object.instantiate (http://localhost:9000/bower_components/angular/angular.js:3721:23) <div ui-view="" class="ng-scope">

**Comment by wcandillon** [comment]
@gislenius The new reports are missing the `Id` property in presentation elements.

**Comment by wcandillon** [comment]
@gislenius I think a good way to deal with this would be to add the Ids automatically in https://github.com/28msec/cellstore/blob/master/tasks/templates/UpdateReportSchema.jq.mustache
@dknochen Do you agree?

**Comment by gislenius** [comment]
Hi,
This is now fixed.

Further issues:
1. xbrl28:ImpliedTable is hardcoded. The error is "TypeError: Cannot read property 'Aspects' of undefined". I tried changing 

    model.Hypercubes['xbrl28:ImpliedTable']

to

    model.Hypercubes[0]

but the error is still here.

2. Formulas don't appear in the editor.

**Comment by dknochen** [comment]
image

**Comment by gislenius** [comment]
Wow! What did you do?

**Comment by dknochen** [comment]
@gislenius it was fixed by adding some missing dimensions

**Comment by dknochen** [comment]
@gislenius you need to do the merging with master
There is a conflict in queries/public/api/facttable-for-report.jq
thank you :)

**Pull request merged**
