### PR TITLE
Apidoc ui improvements for facts endpoint

### PR DESCRIPTION
**Pull request by dknochen**

### CODE REVIEW

**Comment by dknochen** [comment]
the second added example depends on this fix: https://github.com/wcandillon/swagger-js-codegen/pull/46

**Comment by wcandillon** [comment]
@dknochen Should the backend and frontend change be submitted separately? Ghislain can review the backend and I can review the frontend.

**Comment by wcandillon** [comment]
I played with it, looks great so far!

**Comment by wcandillon** [comment]
Check exception cases.

**Comment by wcandillon** [comment]
Add example:
http://edinet.28.io/v1/_queries/public/api/periods.jq?_method=POST&token=54eb0587-1aee-44a5-bb56-627f6ef43da6&tag=ALL&fiscalYear=2013&fiscalYear=2014
http://edinet.28.io/v1/_queries/public/api/periods.jq?_method=POST&token=54eb0587-1aee-44a5-bb56-627f6ef43da6&tag=ALL&fiscalPeriod=Q1&fiscalPeriod=Q2

**Comment by dknochen** [comment]
the filtering by eid / xbrl:Entity doesn't work, yet.

**Comment by dknochen** [comment]
@wcandillon could you publish swagger-js-codegen 0.3.8? Its blocked on it. Thank you.

**Comment by wcandillon** [comment]
done

**Comment by dknochen** [comment]
@wcandillon do you have time to review this? Otherwise, Ghislain and I will just go on and merge it. Then the improved examples in the facttable branch will work.

**Comment by wcandillon** [comment]
@dknochen I approve it.

**Comment by wcandillon** [comment]
@gislenius Are you fine with the backend changes in this branch?

**Comment by gislenius** [comment]
@wcandillon yes

**Pull request merged**
