### PR TITLE
fix register button

### LINKED ISSUE #982: Register Button Doesn't work for secxbrl.info
@dknochen Can you look into this? At the moment it prevents people from creating an account since we've updated the website.

### PR DESCRIPTION
**Pull request by dknochen**
:bug: temporary fix #982

### CODE REVIEW

**Comment by dknochen** [comment]
@wcandillon its a temporary fix as we plan to move the registration.

**Comment by wcandillon** [comment]
meh :-/

But I guess I'll take it for now.

**Comment by wcandillon** [comment]
@dknochen Moving the registration should be trivial no? Is it more than cut/paste of the code? What am I missing?

**Comment by wcandillon** [comment]
@dknochen I fixed the tests, it gave me a bit of a sweat ;-)) :sweat_smile:

**Comment by dknochen** [comment]
@wcandillon  wow cool :smiley: what was the problem?

**Comment by wcandillon** [comment]
hahahaha we'll never know. I upgraded to protractor 2.0 and everything worked. Protractor 2.0 looks cool. I'll ask circleci support if we can use server x for debugging or something.

**Pull request merged**
