### PR TITLE
Two fixes.

### PR DESCRIPTION
**Pull request by gislenius**

### CODE REVIEW

**Comment by dknochen** [comment]
@gislenius the fix looks good to me :+1: . Could you add a test that used to fail before this fix? Thank you.

**Comment by gislenius** [comment]
@dknochen Writing tests is not straightforward, as nothing in the secxbrl or edinet would be an example of fails-to-succeeds behavior. These errors were fixed against the early Swiss taxonomy. The first error prevents a crash if some labels are set to null (which normally should not happen if it comes from the infoset generator). The second error prevents an empty spreadsheet from appearing as broken, by forcing at least an empty column.

**Comment by dknochen** [comment]
@gislenius Maybe, we have to generate swissxbrl-6 with dummy labels then instead of nulls?

**Comment by gislenius** [comment]
Hi Dennis, that's a good point. I would also be fine with this.

**Pull request merged**
