### PR TITLE
Fixing XML serialization for generic and Japan profiles.

### PR DESCRIPTION
**Pull request by gislenius**

### CODE REVIEW

**Comment by wcandillon** [comment]
Awesome!

**Comment by gislenius** [comment]
Thanks William ;-)

**Comment by fcavalieri** [comment]
@gislenius Hi Ghislain, do you think it would make sense to add a test to check the produced xml?

**Comment by gislenius** [comment]
Hi Federico,

I added a test and took the opportunity to completely refactor tests on the edinet side. We can refactor the secxbrl side later, which should be straightforward to do.

**Comment by fcavalieri** [comment]
Hi Ghislain, awesome! Feel free to merge when the tests pass! :+1:

**Pull request merged**
