### PR TITLE
Mark sec specific parameters

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by dknochen** [comment]
yes, I agree. Can we make it arrays? Also the japan branch merge introduces a new endpoint in the swagger file that needs adaptation as well.

**Comment by dknochen** [comment]
the cellstore profile is called sec. That's what we should use I think. secxbrl is the deployment.

**Comment by dknochen** [comment]
after renaming secxbrl -> sec we can merge.

**Comment by wcandillon** [comment]
@dknochen make sense thks!

**Pull request merged**
