### PR TITLE
Abstract filtering

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
Would it make sense to add `onlyTextBlocks` and `abstract` to `labels.jq`?

**Comment by gislenius** [comment]
Hi William,

I will later do a major improvement of report element classification which should involve these parameters as well. I would rather polish then and stick to what corresponds to needed use cases.

Kind regards,
Ghislain

**Comment by gislenius** [comment]
Hi @wcandillon,

If you agree, that's good to go.

Kind regards,
Ghislain

**Comment by wcandillon** [comment]
@gislenius Right now the use case is to have it on `labels.jq` because this what we use in the dashboard. But I agree that this has low priority.

**Pull request merged**
