### PR TITLE
Remove deprecated, unused functions.

### PR DESCRIPTION
**Pull request by gislenius**

### CODE REVIEW

**Comment by gislenius** [comment]
... and there you go @dknochen ;-)

**Comment by dknochen** [comment]
@gislenius did you test that the call to TotalForConceptGroupedByFiscalPeriodForAllEntities.jq still works? Adding a test for it would be too heavy weight, right?

**Comment by gislenius** [comment]
@dknochen good catch, but it's already broken on master. I raised an issue.

https://github.com/28msec/cellstore/issues/953

I don't think it should block this PR.

**Comment by dknochen** [comment]
@gislenius I agree. Thank you. :)

**Pull request merged**
