### PR TITLE
No mustache

### PR DESCRIPTION
**Pull request by dknochen**

### CODE REVIEW

**Comment by wcandillon** [comment]
@dknochen Looks good. Can you give me more info on the motivation for this? Why is it done on these file specifically and not everywhere?

**Comment by dknochen** [comment]
@wcandillon I need this change to be able to define multiple datasources in the encrypted config. We need to add an elastic search data source. With mustache it simply doesn't work.

**Comment by wcandillon** [comment]
@dknochen I would be happy to review and merge this but the branch is conflicting.

**Comment by dknochen** [comment]
superseded: https://github.com/28msec/cellstore/pull/800

**Pull request closed without merging**
