### PR TITLE
Count

### PR DESCRIPTION
**Pull request by gislenius**
Customer request: perform a count only, without downloading the actual data (faster performance).

### CODE REVIEW

**Comment by gislenius** [comment]
http://edinet-dev.28.io/v1/_queries/public/api/facts.jq?token=foobar&ticker=7751&fiscalYear=2014&fiscalPeriod=FY&count

**Comment by dknochen** [comment]
the actual user request could be added as example and sec test.

**Comment by dknochen** [comment]
Very clean PR. I like that :)!

**Comment by gislenius** [comment]
@dknochen the use case has been added to both the documentation and tests. It will be faster once we have the entity index on the facts collection.

**Pull request merged**
