### PR TITLE
Add DELETE method to filings.jq.

### PR DESCRIPTION
**Pull request by ghislainfourny**

### CODE REVIEW

**Comment by ghislainfourny** [comment]
TODO:
- add admin token to config file
- set up a test database with write access
- have tests (i) insert an archive into the database (ii) test it's here (iii) delete it (iv) test it's no longer here
- test for unauthorized with test token

**Comment by ghislainfourny** [comment]
Needs dropping the error "A sequential query cannot be invoked using GET" in a subsequent 28.io release.

**Comment by wcandillon** [comment]
@ghislainfourny We can discuss this offline. I recommend to have the `DELETE` method handled in a separate query in the meantime.

**Comment by wcandillon** [comment]
Two small comments:
* While we have an automatic rest mapping, maybe `-DELETE` as a suffix is not user friendly enough? (no strong opinon)
* No tests?

**Comment by wcandillon** [comment]
@fcavalieri this seems to be a good candidate for the new URL rewriter infrastructure.

**Pull request merged**
